### ISSUE TITLE
Newline in secret causes failure

### ISSUE THREAD

**Issue by johnjcamilleri** [golfzaptw/action-connect-ovpn#44]
**Describe the bug**
If any of the secrets end in a newline (which can easily happen when copy+pasting), one gets an error:

```
/bin/sh: 2: Syntax error: "|" unexpected
##[error]Can't create file ca.crt
```

**To Reproduce**
1. Save secret `CA_CRT` ending with a newline
2. Specify `env.CA_CRT: ${{ secrets.CA_CRT }}` in action file

**Comment by golfzaptw** [comment]
@johnjcamilleri Why you need to save CA_CRT ending with a newline because I recommend setting secrets.CA_CRT with a encode base64 then my script will generate with decode base64 from secrets.CA_CRT

**Comment by johnjcamilleri** [comment]
I don't _need_ to have an newline, but it can easily happen when copy/pasting and took a while to figure out what was wrong.

**Comment by golfzaptw** [comment]
ok, so I will add trim for all input
