### ISSUE TITLE
[DOCUMENT] Improve docs for SECRET 

### ISSUE THREAD

**Issue by albertgnetwork** [golfzaptw/action-connect-ovpn#96]
The description for setting up `SECRET:  ${{ secrets.SECRET_USERNAME_PASSWORD }}` is very confusing:

_If your open vpn configuration has a username and password please encode those in base64. After that, save the values in the github actions secrets. format username password username-vpn password-vpn_

Especially the last sentence. Could you please clarify the format? Why do we have both username and username-vpn?

**Comment by IliaBulavintsev** [comment]
@golfzaptw Any updates?

**Comment by AvinashKulal** [comment]
@golfzaptw  Any progress?

**Comment by lamemind-ud** [comment]
Could anyone share an example that shows the required format?

**Comment by jf-marino** [comment]
For anyone interested it seems the right format is to use username and password with a newline like this
```
username
password
```
Encoding that into base64 and loading that into a secret.
Its mentioned in [this comment](https://github.com/golfzaptw/action-connect-ovpn/issues/26#issuecomment-603727043).
Also note that you need to include the line
```
auth-user-pass secret.txt
```
in your config.ovpn for the username and password to load correctly.
